version:  '3'

services:

  backend:
    restart: always
    build: ./backend
    ports:
      - "5000:5000"
    env_file: test_docker.env
    working_dir: /backend
    links:
      - db
    depends_on:
      - db


    

  frontend:
    image: node:latest
    volumes:
      - ./frontend:/frontend
    env_file: test_docker.env
    working_dir: /frontend
    command: npm start
    ports:
      - "3000:3000"



    
 #ginx:
 # restart: always
 # build: ./nginx
 # volumes:
 #   - frontend_static:/frontend
 # links:
 #   - backend:uwsgi
 # ports:
 #   - "80:80"
 # depends_on:
 #   - backend
 # env_file: test_docker.env
    
  
  db:
    restart: always
    image: mysql:5.7
    env_file: test_docker.env
    volumes: 
      - ./mysql/data/db:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    expose:
      - 3306
    ports:
      - "3307:3306"

#volumes:
#  frontend_static:

    
    
    
      
    