"""empty message

Revision ID: 4dbbc7eb5d3e
Revises: 7b6c15e4c510
Create Date: 2019-01-09 20:52:57.018650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4dbbc7eb5d3e'
down_revision = '7b6c15e4c510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True))
    # ### end Alembic commands ###
