"""empty message

Revision ID: 72201d7c3eed
Revises: bae90d89fe0e
Create Date: 2019-01-16 22:03:48.642459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72201d7c3eed'
down_revision = 'bae90d89fe0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('receive_user_id', sa.String(length=64), nullable=True))
    op.add_column('message', sa.Column('send_user_id', sa.String(length=64), nullable=True))
    op.drop_constraint('message_ibfk_1', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'user', ['receive_user_id'], ['id'])
    op.create_foreign_key(None, 'message', 'user', ['send_user_id'], ['id'])
    op.drop_column('message', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('author_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_ibfk_1', 'message', 'user', ['author_id'], ['id'])
    op.drop_column('message', 'send_user_id')
    op.drop_column('message', 'receive_user_id')
    # ### end Alembic commands ###
