"""empty message

Revision ID: 813e14f9052e
Revises: db59e1d57b8a
Create Date: 2019-01-13 21:13:13.223667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '813e14f9052e'
down_revision = 'db59e1d57b8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collects',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('topic_id', sa.String(length=64), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'topic_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collects')
    # ### end Alembic commands ###
