"""empty message

Revision ID: db59e1d57b8a
Revises: 4dbbc7eb5d3e
Create Date: 2019-01-13 09:59:37.287974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db59e1d57b8a'
down_revision = '4dbbc7eb5d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('tab', sa.String(length=64), nullable=True))
    op.drop_column('topic', 'tabe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('tabe', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True))
    op.drop_column('topic', 'tab')
    # ### end Alembic commands ###
